CREATE TABLE modelo(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    marca_id INTEGER NOT NULL,
    nome VARCHAR(255) NOT NULL,
    valor_FIPE DOUBLE NOT NULL,
    CONSTRAINT modelo_marca_id_fkey FOREIGN KEY (marca_id) REFERENCES marca (id) ON DELETE RESTRICT ON UPDATE CASCADE
);